# Generated by Django 2.1.2 on 2018-11-01 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.PositiveSmallIntegerField(choices=[(1, 'Sick Leave'), (2, 'Paid Leave'), (3, 'Unpaid Leave'), (4, 'Annual Leave'), (5, 'Family Leave')], verbose_name='leave type')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='month')),
                ('year', models.PositiveSmallIntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027')], default=2018, verbose_name='year')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('leave_status', models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Allowed'), (3, 'Denied'), (4, 'Processed')], default=1, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee.Employee', verbose_name='employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_by', to='employee.Employee', verbose_name='processed by')),
            ],
        ),
    ]
