# Generated by Django 2.1.2 on 2018-11-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('short_code', models.CharField(max_length=3, unique=True, verbose_name='short code')),
                ('icon', models.ImageField(blank=True, upload_to='currency/', verbose_name='icon')),
                ('icon1', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon 1')),
                ('icon2', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon 2')),
                ('icon3', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon 3')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyType', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=255, verbose_name='currency_type')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_countries', to='contact.Country', verbose_name='country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_countries', to='currency.Currency', verbose_name='currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='currencycountry',
            unique_together={('currency', 'country')},
        ),
    ]
