# Generated by Django 2.1.2 on 2018-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='short_code',
            field=models.CharField(max_length=3, verbose_name='short code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
