# Generated by Django 2.1.2 on 2018-11-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('contact', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='designation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.Company', verbose_name='company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='auth.Group', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type_weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='weight')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_types', to='company.Company', verbose_name='company')),
            ],
        ),
    ]
