# Generated by Django 2.1.2 on 2018-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20181209_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='resume'),
        ),
    ]
