# Generated by Django 2.1.2 on 2019-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_monthly_committed_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_committed_hour',
            field=models.IntegerField(default=0, verbose_name='committed hour( monthly )'),
        ),
    ]
