# Generated by Django 2.1.2 on 2018-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20181112_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='dialing code'),
        ),
    ]
