# Generated by Django 2.1.2 on 2018-11-01 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='hours')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
