# Generated by Django 2.1.2 on 2018-12-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20181209_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedhour',
            old_name='employee',
            new_name='project',
        ),
    ]
