# Generated by Django 2.1.2 on 2018-12-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20181212_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedhour',
            options={'ordering': ('-created_at',)},
        ),
    ]
