# Generated by Django 2.1.2 on 2019-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20190117_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedhour',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='hours'),
        ),
    ]
