# Generated by Django 2.1.2 on 2019-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20190130_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedhour',
            name='minute',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='minute'),
        ),
    ]
