# Generated by Django 2.1.2 on 2019-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_reportedhour_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedhour',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='reportedhour',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='income'),
        ),
        migrations.AddField(
            model_name='reportedhour',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='profit'),
        ),
    ]
