# Generated by Django 2.1.2 on 2019-09-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('reporting', '0010_auto_20190910_0535'),
        # ('project', '0007_project_jira_project_key'),
        ('reporting', '0009_auto_20190222_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedhour',
            name='is_billable',
            field=models.BooleanField(default=True, verbose_name='is billable'),
        ),
    ]
