# Generated by Django 2.1.2 on 2019-09-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_jira_project_key'),
        ('reporting', '0011_reportedhour_is_billable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportedhour',
            unique_together={('project_employee', 'date', 'is_billable')},
        ),
    ]
