# Generated by Django 2.1.2 on 2018-12-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181209_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployee',
            name='assigned_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employees', to='employee.EmployeeType', verbose_name='assigned as'),
        ),
    ]
