# Generated by Django 2.1.2 on 2019-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20181209_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectemployee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30, verbose_name='status'),
        ),
    ]
