# Generated by Django 2.1.2 on 2019-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectemployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='income'),
        ),
    ]
