# Generated by Django 2.1.2 on 2019-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
